[2022-07-09 23:12:37,670]^;INFO^;86^;configuration.py^;get_training_pipeline_config()^;Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\somit\\Downloads\\project_ineuron\\practise_project_1\\housing\\artifact')
[2022-07-09 23:12:37,671]^;INFO^;65^;configuration.py^;get_data_ingestion_config()^;Data Ingestion config: DataIngestionConfig(dataset_download_url='https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz', tgz_download_dir='C:\\Users\\somit\\Downloads\\project_ineuron\\practise_project_1\\housing\\artifact\\data_ingestion\\2022-07-09-23-12-36\\tgz_data', raw_data_dir='C:\\Users\\somit\\Downloads\\project_ineuron\\practise_project_1\\housing\\artifact\\data_ingestion\\2022-07-09-23-12-36\\raw_data', ingested_train_dir='C:\\Users\\somit\\Downloads\\project_ineuron\\practise_project_1\\housing\\artifact\\data_ingestion\\2022-07-09-23-12-36\\ingested_data\\train', ingested_test_dir='C:\\Users\\somit\\Downloads\\project_ineuron\\practise_project_1\\housing\\artifact\\data_ingestion\\2022-07-09-23-12-36\\ingested_data\\test')
[2022-07-09 23:12:37,671]^;INFO^;16^;data_ingestion.py^;__init__()^;>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Data Ingestion log started.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
[2022-07-09 23:12:37,671]^;INFO^;37^;data_ingestion.py^;download_housing_data()^;Downloading file from :[https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz] into :[C:\Users\somit\Downloads\project_ineuron\practise_project_1\housing\artifact\data_ingestion\2022-07-09-23-12-36\tgz_data\housing.tgz]
[2022-07-09 23:12:38,620]^;INFO^;39^;data_ingestion.py^;download_housing_data()^;File :[C:\Users\somit\Downloads\project_ineuron\practise_project_1\housing\artifact\data_ingestion\2022-07-09-23-12-36\tgz_data\housing.tgz] has been downloaded successfully.
[2022-07-09 23:12:38,620]^;ERROR^;23^;demo.py^;main()^;
        Error occured in script: 
        [ C:\Users\somit\Downloads\project_ineuron\practise_project_1\housing\pipeline\pipeline.py ] at 
        try block line number: [37] and exception block line number: [40] 
        error message: [
        Error occured in script: 
        [ C:\Users\somit\Downloads\project_ineuron\practise_project_1\housing\pipeline\pipeline.py ] at 
        try block line number: [27] and exception block line number: [30] 
        error message: [
        Error occured in script: 
        [ C:\Users\somit\Downloads\project_ineuron\practise_project_1\housing\component\data_ingestion.py ] at 
        try block line number: [121] and exception block line number: [124] 
        error message: [
        Error occured in script: 
        [ C:\Users\somit\Downloads\project_ineuron\practise_project_1\housing\component\data_ingestion.py ] at 
        try block line number: [49] and exception block line number: [59] 
        error message: [testing exception]
        ]
        ]
        ]
        
[2022-07-09 23:12:38,623]^;INFO^;129^;data_ingestion.py^;__del__()^;>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Data Ingestion log completed.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 


